<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'KrokedilKlarnaPaymentsDeps\\Krokedil\\WpApi\\' => array($vendorDir . '/krokedil/wp-api/src'),
    'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\' => array($vendorDir . '/krokedil/woocommerce/src'),
    'KrokedilKlarnaPaymentsDeps\\Krokedil\\Support\\' => array($vendorDir . '/krokedil/support/src'),
    'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\' => array($vendorDir . '/krokedil/settings-page/src'),
);
